// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type ExchangeRate struct {
	ID           int32
	FromCurrency string
	ToCurrency   string
	Rate         string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
